FROM python:3.8-alpine

# Install libaries
RUN apk update && apk add \
build-base \
cairo-dev \
gdk-pixbuf-dev \
glib-dev \
libjpeg-turbo-dev \
libxml2-dev \
openjpeg-dev \
sqlite-dev \
tiff-dev \
zlib-dev \
autoconf \
automake \
libtool \
pkgconfig \
curl

ARG OPENSLIDE_VERSION=46a0706506c6cca8f1fbb51f49516721b6d5c9d0
RUN curl -fL https://github.com/openslide/openslide/archive/${OPENSLIDE_VERSION}.zip -o openslide.zip \
&& unzip openslide.zip \
&& cd openslide-${OPENSLIDE_VERSION} \
&& autoreconf -i \
&& ./configure \
&& make \
&& make install
ENV LD_LIBRARY_PATH=/usr/local/lib/

RUN pip3 install --user openslide-python
ADD ./test.py /root/test.py
ENV PATH=${PATH}:/root
